//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserLogin
    {
        public string LoginProvider { get; set; }
        public string ProviderKey { get; set; }
        public int USERID { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public string System { get; set; }
        public string UserLoginTypeId { get; set; }
        public string MobileNumber { get; set; }
        public string MacAddres { get; set; }
        public string IPAddress { get; set; }
    }
}
