//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGroupParticipant
    {
        public int GroupParticipantId { get; set; }
        public int GroupId { get; set; }
        public int USERID { get; set; }
        public Nullable<int> ParticipantGroupId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public string CreatedById { get; set; }
        public string ModifiedById { get; set; }
    }
}
