//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int id { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
