//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityMaster
    {
        public int FacilityMasterId { get; set; }
        public string FacilityMasterName { get; set; }
        public int OrganisationId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Landmark { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string FacilityType { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public string CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedById { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<decimal> SessionTimeout { get; set; }
        public Nullable<int> ZipId { get; set; }
    }
}
