//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageSetting
    {
        public int MessageSettingsId { get; set; }
        public string StoragePath { get; set; }
        public string Font { get; set; }
        public string Language { get; set; }
        public string Size { get; set; }
        public Nullable<int> AutoArchivePeriod { get; set; }
        public string CanBroadcast { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public string CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedById { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
