//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kryptoEntities1 : DbContext
    {
        public kryptoEntities1()
            : base("name=kryptoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<ChatGroupParticipant> ChatGroupParticipants { get; set; }
        public DbSet<ChatGroup> ChatGroups { get; set; }
        public DbSet<DeviceTokenInformation> DeviceTokenInformations { get; set; }
        public DbSet<GroupActivitiesType> GroupActivitiesTypes { get; set; }
        public DbSet<GroupType> GroupTypes { get; set; }
        public DbSet<KPTY_USER_FORGOT_PASS_OTP_REQ_TBL> KPTY_USER_FORGOT_PASS_OTP_REQ_TBL { get; set; }
        public DbSet<KPTY_USER_OTP_EXPIRY_TIME_TBL> KPTY_USER_OTP_EXPIRY_TIME_TBL { get; set; }
        public DbSet<KPTY_USER_SECQURITY_QUEST_ANS> KPTY_USER_SECQURITY_QUEST_ANS { get; set; }
        public DbSet<MenuGroup> MenuGroups { get; set; }
        public DbSet<MenuGroupMenuOption> MenuGroupMenuOptions { get; set; }
        public DbSet<MenuOption> MenuOptions { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageSetting> MessageSettings { get; set; }
        public DbSet<MessageTransaction> MessageTransactions { get; set; }
        public DbSet<MobileTypeMaster> MobileTypeMasters { get; set; }
        public DbSet<Organisation> Organisations { get; set; }
        public DbSet<OtpStatusMaster> OtpStatusMasters { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Title> Titles { get; set; }
        public DbSet<UserActivate> UserActivates { get; set; }
        public DbSet<UserFacility> UserFacilities { get; set; }
        public DbSet<UserForgotMpinsOTP> UserForgotMpinsOTPS { get; set; }
        public DbSet<UserRegisterdContact> UserRegisterdContacts { get; set; }
        public DbSet<UserRegistrationOTP> UserRegistrationOTPs { get; set; }
        public DbSet<UserRegitrationForInitialLogin> UserRegitrationForInitialLogins { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<UserSecurityQuestion> UserSecurityQuestions { get; set; }
        public DbSet<UserSessionTokenApiCalltbl> UserSessionTokenApiCalltbls { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<ZipCode> ZipCodes { get; set; }
        public DbSet<GroupActivity> GroupActivities { get; set; }
        public DbSet<FacilityMaster> FacilityMasters { get; set; }
        public DbSet<UserLoginInformation> UserLoginInformations { get; set; }
    }
}
