//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegitrationForInitialLogin
    {
        public decimal Id { get; set; }
        public int USERID { get; set; }
        public bool IsInitialLogin { get; set; }
        public bool IsTermsAccepted { get; set; }
        public bool IsSecQuestEnabled { get; set; }
        public bool IsMpinCreated { get; set; }
        public bool IsPasswordUpdated { get; set; }
        public System.DateTime Createdate { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public string CreatedById { get; set; }
        public string ModifiedById { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
