//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginInformation
    {
        public int USERID { get; set; }
        public string AspUserId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public bool UserIsActive { get; set; }
        public string Title { get; set; }
        public string Employer { get; set; }
        public string Field { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string SecurityQuestion1 { get; set; }
        public string SecurityQuestion2 { get; set; }
        public string SecurityAnswer1 { get; set; }
        public string SecurityAnswer2 { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProfileURL { get; set; }
        public string MPIN { get; set; }
        public string Notes { get; set; }
        public string CreatedById { get; set; }
        public string ModifiedById { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public string ContactNumber { get; set; }
        public string Organisations { get; set; }
        public Nullable<int> ZipId { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
        public bool IsSuperAdmin { get; set; }
        public bool IsOrganisationAdmin { get; set; }
        public bool IsFacilityAdmin { get; set; }
        public bool IsNormalUser { get; set; }
    }
}
