//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivate
    {
        public int Id { get; set; }
        public int USERID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CreatedById { get; set; }
    }
}
